all:
	g++ -std=c++17 main.cpp -o global_search_omp -fopenmp
	./global_search_omp input2.txt

mac:
	g++-14 -fopenmp -std=c++17 main.cpp -o global_search_omp 
	./global_search_omp ../inputs/graph_6_nodes.txt